Models/Directorio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;

namespace DirectorioSahuro.Models
{
    public class Directorio
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "El Nombre es requerido")]
        public string NOMBRE { get; set; }

        [Required(ErrorMessage = "Fecha de Nacimiento requerida")]
        public DateTime FECHA_NACIMIENTO { get; set; }

        public string FOTOGRAFIA { get; set; }

        [Required(ErrorMessage = "Telefono(s) requerido")]
        public string TELEFONOS { get; set; }
    }

    public class DirectorioDBContext : DbContext
    {
        public DbSet<Directorio> Directorio { get; set; }
    }
}

Controllers/DirectorioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DirectorioSahuro.Models;
using System.IO;
using DevExpress.Web.Mvc;

namespace DirectorioSahuro.Controllers
{
    public class DirectorioController : Controller
    {
        private DirectorioDBContext db = new DirectorioDBContext();

        //
        // GET: /Directorio/

        public ViewResult Index()
        {
            return View(db.Directorio.OrderBy(a => a.NOMBRE).ToList());
        }

        //
        // GET: /Directorio/Details/5

        public ViewResult Details(int id)
        {
            Directorio directorio = db.Directorio.Find(id);
            return View(directorio);
        }

        //
        // GET: /Directorio/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Directorio/Create

        [HttpPost]
        public ActionResult Create(Directorio directorio, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Directorio.Add(directorio);
                db.SaveChanges();
                //Saving image
                if (file != null)
                {
                    string pic = directorio.ID.ToString() + "." + System.IO.Path.GetFileName(file.ContentType);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/ProfileImages"), pic);
                    file.SaveAs(path);
                    directorio.FOTOGRAFIA = "Content/ProfileImages/" + pic + "";
                    db.SaveChanges();
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }
                else
                {
                    directorio.FOTOGRAFIA = "Content/ProfileImages/no_image.png";
                    db.SaveChanges();
                }
                //
                return RedirectToAction("Index");
            }

            return View(directorio);
        }

        //
        // GET: /Directorio/Edit/5

        public ActionResult Edit(int id)
        {
            Directorio directorio = db.Directorio.Find(id);
            return View(directorio);
        }

        //
        // POST: /Directorio/Edit/5

        [HttpPost]
        public ActionResult Edit(Directorio directorio, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                db.Entry(directorio).State = EntityState.Modified;
                db.SaveChanges();
                //Delete actual image and save the new one
                if (!directorio.FOTOGRAFIA.Contains("no_image.png"))
                {
                    System.IO.File.Delete(Server.MapPath("~/" + directorio.FOTOGRAFIA));
                }
                if (file != null)
                {
                    string pic = directorio.ID.ToString() + "." + System.IO.Path.GetFileName(file.ContentType);
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/ProfileImages"), pic);
                    file.SaveAs(path);
                    directorio.FOTOGRAFIA = "Content/ProfileImages/" + pic + "";
                    db.SaveChanges();
                    using (MemoryStream ms = new MemoryStream())
                    {
                        file.InputStream.CopyTo(ms);
                        byte[] array = ms.GetBuffer();
                    }
                }
                else
                {
                    directorio.FOTOGRAFIA = "Content/ProfileImages/no_image.png";
                    db.SaveChanges();
                }
                //
                return RedirectToAction("Index");
            }
            return View(directorio);
        }

        //
        // GET: /Directorio/Delete/5

        public ActionResult Delete(int id)
        {
            Directorio directorio = db.Directorio.Find(id);
            return View(directorio);
        }

        //
        // POST: /Directorio/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Directorio directorio = db.Directorio.Find(id);
            db.Directorio.Remove(directorio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        DirectorioSahuro.Models.DirectorioDBContext db1 = new DirectorioSahuro.Models.DirectorioDBContext();

        [ValidateInput(false)]
        public ActionResult GridView3Partial()
        {
            var model = db1.Directorio;
            return PartialView("_GridView3Partial", model.Select(a => new { ID = a.ID, NOMBRE = a.NOMBRE, FECHA_NACIMIENTO = a.FECHA_NACIMIENTO, TELEFONOS = a.TELEFONOS, FOTOGRAFIA = ("<img src='" + a.FOTOGRAFIA + "' alt='NO_IMAGE' height='60px' width='60px'/>") }).OrderBy(a => a.NOMBRE).ToList());
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult GridView3PartialAddNew([ModelBinder(typeof(DevExpressEditorsBinder))] DirectorioSahuro.Models.Directorio item)
        {
            var model = db1.Directorio;
            if (ModelState.IsValid)
            {
                try
                {
                    model.Add(item);
                    db1.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return PartialView("_GridView3Partial", model.ToList());
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult GridView3PartialUpdate([ModelBinder(typeof(DevExpressEditorsBinder))] DirectorioSahuro.Models.Directorio item)
        {
            var model = db1.Directorio;
            if (ModelState.IsValid)
            {
                try
                {
                    var modelItem = model.FirstOrDefault(it => it.ID == item.ID);
                    if (modelItem != null)
                    {
                        this.UpdateModel(modelItem);
                        db1.SaveChanges();
                    }
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            else
                ViewData["EditError"] = "Please, correct all errors.";
            return PartialView("_GridView3Partial", model.ToList());
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult GridView3PartialDelete(System.Int32 ID)
        {
            var model = db1.Directorio;
            if (ID >= 0)
            {
                try
                {
                    var item = model.FirstOrDefault(it => it.ID == ID);
                    if (item != null)
                        model.Remove(item);
                    db1.SaveChanges();
                }
                catch (Exception e)
                {
                    ViewData["EditError"] = e.Message;
                }
            }
            return PartialView("_GridView3Partial", model.ToList());
        }
    }
}

Views/Directorio/Create.cshtml
@model DirectorioSahuro.Models.Directorio
@{
    ViewBag.Title = "Nuevo Contacto";
}
<h2>
    Registrar Nuevo Contacto</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm(Html.BeginForm("Create", "Directorio", FormMethod.Post,
                            new { enctype = "multipart/form-data" })))
{
    @Html.ValidationSummary(true)
        
    <fieldset>
        <legend>Directorio</legend>
        <label for="file">
            Seleacciona la imagen de perfil del contacto:</label>
        <input type="file" name="file" id="file" style="width: 100%;" />
        <hr />
        <div class="editor-label">
            @Html.LabelFor(model => model.NOMBRE)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NOMBRE)
            @Html.ValidationMessageFor(model => model.NOMBRE)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FECHA_NACIMIENTO)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FECHA_NACIMIENTO)
            @Html.ValidationMessageFor(model => model.FECHA_NACIMIENTO)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TELEFONOS) (Puedes escribir varios números de teléfono
            separados por coma (,))
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TELEFONOS)
            @Html.ValidationMessageFor(model => model.TELEFONOS)
        </div>
        <hr />
        <p>
            <input type="submit" value="Guardar Contacto" class="submit" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Regresar al Directorio", "Index")
</div>

Views/Directorio/Delete.cshtml
@model DirectorioSahuro.Models.Directorio
@{
    ViewBag.Title = "Eliminar Contacto";
}
<h2>
    Eliminar contacto</h2>
<h3>
    ¿Estás seguro de que deseas eliminar el contacto seleccionado?</h3>
<table width="100%">
    <tr>
        <td style="width: 110px">
            <b>Fotografía del Contacto</b>
        </td>
        <td>
            <b>Datos de Contacto</b>
        </td>
    </tr>
    <tr>
        <td align="center">
            <img src='../../@Html.DisplayFor(model => model.FOTOGRAFIA)' alt="NO_IMAGE" height="100px" width="100px" />
        </td>
        <td>
            <div class="display-label">
                <b>NOMBRE</b></div>
            <div class="display-field">
                @Html.DisplayFor(model => model.NOMBRE)
            </div>
            <div class="display-label">
                <b>FECHA_NACIMIENTO</b></div>
            <div class="display-field">
                @DateTime.Parse(Html.DisplayFor(model => model.FECHA_NACIMIENTO).ToString()).ToString("D")
            </div>
            <div class="display-label">
                <b>TELEFONOS</b></div>
            <div class="display-field">
                @{
                    string telefonos = (Html.DisplayFor(model => model.TELEFONOS)).ToString();
                    foreach (string a in telefonos.Split(','))
                    {
                    <p>@a</p>
                    }
                }
            </div>
        </td>
    </tr>
</table>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Eliminar Contacto" />
        |
        @Html.ActionLink("Regresar al Directorio", "Index")
    </p>
}

Views/Directorio/Details.cshtml
@model DirectorioSahuro.Models.Directorio
@{
    ViewBag.Title = "Detalles de Contacto";
}
<table width="100%">
    <tr>
        <td style="width: 110px">
            <b>Fotografía del Contacto</b>
        </td>
        <td>
            <b>Datos de Contacto</b>
        </td>
    </tr>
    <tr>
        <td align="center">
            <img src='../../@Html.DisplayFor(model => model.FOTOGRAFIA)' alt="NO_IMAGE" height="100px" width="100px" />
        </td>
        <td>
            <div class="display-label">
                <b>NOMBRE</b></div>
            <div class="display-field">
                @Html.DisplayFor(model => model.NOMBRE)
            </div>
            <div class="display-label">
                <b>FECHA_NACIMIENTO</b></div>
            <div class="display-field">
                @DateTime.Parse(Html.DisplayFor(model => model.FECHA_NACIMIENTO).ToString()).ToString("D")
            </div>
            <div class="display-label">
                <b>TELEFONOS</b></div>
            <div class="display-field">
                @{
                    string telefonos = (Html.DisplayFor(model => model.TELEFONOS)).ToString();
                    foreach (string a in telefonos.Split(','))
                    {
                    <p>@a</p>
                    }
                }
            </div>
        </td>
    </tr>
</table>
<p>
    @Html.ActionLink("Editar Contacto", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Regresar al Directorio", "Index")
</p>

Views/Directorio/Edit.cshtml
@model DirectorioSahuro.Models.Directorio
@{
    ViewBag.Title = "Editar Contacto";
}
<h2>
    Editar Contacto</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
@using (Html.BeginForm(Html.BeginForm("Edit", "Directorio", FormMethod.Post,
                            new { enctype = "multipart/form-data" })))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Directorio</legend>
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.FOTOGRAFIA)
        <label for="file">
            Seleacciona la imagen de perfil del contacto:</label>
        <input type="file" name="file" id="file" style="width: 100%;" />
        <hr />
        <div class="editor-label">
            @Html.LabelFor(model => model.NOMBRE)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NOMBRE)
            @Html.ValidationMessageFor(model => model.NOMBRE)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.FECHA_NACIMIENTO)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FECHA_NACIMIENTO)
            @Html.ValidationMessageFor(model => model.FECHA_NACIMIENTO)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.TELEFONOS) (Puedes escribir varios números de teléfono
            separados por coma (,))
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TELEFONOS)
            @Html.ValidationMessageFor(model => model.TELEFONOS)
        </div>
        <p>
            <input type="submit" value="Guardar cambios" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Regresar al Directorio", "Index")
</div>

Views/Directorio/Index.cshtml
@model IEnumerable<DirectorioSahuro.Models.Directorio>
@{
    ViewBag.Title = "Mi Directorio";
}
<h2>
    Mi Directorio</h2>
<p>
    @Html.ActionLink("Nuevo Contacto", "Create")
</p>
<hr />
<h3>
    DevExpress View</h3>
<hr />
@Html.Action("GridView3Partial")
<hr />
<h3>
    Table View</h3>
<hr />
<table>
    <tr id="GridView1_DXHeadersRow0">
        <th>
            FOTOGRAFIA
        </th>
        <th>
            NOMBRE
        </th>
        <th>
            FECHA DE NACIMIENTO
        </th>
        <th>
            TELEFONOS
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td align="center">
                <img src='@Html.DisplayFor(modelItem => item.FOTOGRAFIA)' alt="NO_IMAGE" height="60px" width="60px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NOMBRE)
            </td>
            <td align="center">
                @Html.DisplayFor(modelItem => item.FECHA_NACIMIENTO).ToString().Substring(0, 10)
            </td>
            <td>
                @{
        string telefonos = (Html.DisplayFor(modelItem => item.TELEFONOS)).ToString();
        foreach (string a in telefonos.Split(','))
        {
                    <p>@a</p>
        }
                }
            </td>
            <td>
                @Html.ActionLink("Ver Detalles", "Details", new { id = item.ID }) |
                @Html.ActionLink("Editar Contacto", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Eliminar Contacto", "Delete", new { id = item.ID })
            </td>
        </tr>
    }
</table>

Views/Directorio/_GridView3Partial.cshtml
@{
    var grid = Html.DevExpress().GridView(settings =>
    {
        settings.Name = "GridView3";
        settings.CallbackRouteValues = new { Controller = "Directorio", Action = "GridView3Partial" };

        settings.SettingsEditing.AddNewRowRouteValues = new { Controller = "Directorio", Action = "GridView3PartialAddNew" };
        settings.SettingsEditing.UpdateRowRouteValues = new { Controller = "Directorio", Action = "GridView3PartialUpdate" };
        settings.SettingsEditing.DeleteRowRouteValues = new { Controller = "Directorio", Action = "GridView3PartialDelete" };
        settings.SettingsEditing.Mode = GridViewEditingMode.EditFormAndDisplayRow;
        settings.SettingsBehavior.ConfirmDelete = true;

        settings.CommandColumn.Visible = false;
        settings.CommandColumn.ShowDeleteButton = true;
        settings.CommandColumn.ShowEditButton = true;

        settings.KeyFieldName = "ID";

        settings.SettingsPager.Visible = true;
        settings.Settings.ShowGroupPanel = false;
        settings.Settings.ShowFilterRow = true;
        settings.SettingsBehavior.AllowSelectByRowClick = true;

        settings.Columns.Add(column =>
        {
            column.FieldName = "FOTOGRAFIA";
            column.PropertiesEdit.EncodeHtml = false;
        });
        settings.Columns.Add("NOMBRE");
        settings.Columns.Add("FECHA_NACIMIENTO");
        settings.Columns.Add("TELEFONOS");

        settings.Columns.Add(column =>
        {
            column.Name = "Name";
            column.Caption = "Ver Detalles";

            column.SetDataItemTemplateContent(content =>
                ViewContext.Writer.Write(
                    Html.ActionLink("Ver Detalles", "Details", new { ID = content.KeyValue }, null)));
        });

        settings.Columns.Add(column =>
        {
            column.Name = "Name";
            column.Caption = "Editar";

            column.SetDataItemTemplateContent(content =>
                ViewContext.Writer.Write(
                    Html.ActionLink("Editar Contacto", "Edit", new { ID = content.KeyValue }, null)));
        });

        settings.Columns.Add(column =>
        {
            column.Name = "Name";
            column.Caption = "Eliminar";

            column.SetDataItemTemplateContent(content =>
                ViewContext.Writer.Write(
                    Html.ActionLink("Eliminar Contacto", "Delete", new { ID = content.KeyValue }, null)));
        });
    });
    if (ViewData["EditError"] != null)
    {
        grid.SetEditErrorText((string)ViewData["EditError"]);
    }
}
@grid.Bind(Model).GetHtml()